disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - file_length
opt_in_rules:
  - explicit_init
  - explicit_type_interface
included:
  - Sources
  - Tests
excluded:
  - .build
