name: SwiftLint
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
      - name: SwiftLint
        run: swiftlint lint
        continue-on-error: true
